theme = "gruvbox_dark_hard_custom"

[editor]
cursorline = true
idle-timeout = 200
rulers = [80, 120]
mouse = true
gutters = ["line-numbers", "spacer", "diff"]
bufferline = "multiple"
popup-border = "all"
auto-pairs = false

[editor.statusline]
left = ["file-modification-indicator", "file-name", "version-control"]
center = ["spinner", "mode", "register"]
right = ["primary-selection-length", "diagnostics", "total-line-numbers", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]
